language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - feature-vps
addons:
  apt:
    packages:
      - sshpass
script:
  - npm i
  - npm run eslint
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o StrictHostKeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o StrictHostKeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ./deploy.sh"
