language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - develop
addons:
  apt:
    packages:
      - sshpass
script:
  - npm run eslint
after_success:
  - mkdir archive
  - mv ./src/built archive
  - mv ./index.html archive
  - mv ./src/static/index.html archive
  - tar -czf package.tgz archive
  - scp -o StrictHostKeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass ssh -o StrictHostKeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ./deploy.sh"