language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - develop
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch:
    - develop
before_install:
- openssl aes-256-cbc -K $encrypted_a5968e60f234_key -iv $encrypted_a5968e60f234_iv
  -in id_rsa.enc -out $HOME/.ssh/id_rsa -d